export const KR = {
    OK: "확인",
    SteelMill: "제철 공장",
    StainlessSteelPlant: "스테인리스 공장",
    CircuitFoundry: "Circuit Foundry",
    IntegratedCircuit: "Integrated Circuit",
    OilWell: "석유 시추",
    Wood: "나무",
    LoggingCamp: "벌채 캠프",
    LumberMill: "목재 공장",
    Lumber: "목재",
    Paper: "종이",
    PaperMill: "제지 공장",
    Book: "책",
    BookPublisher: "출판사",
    OilRefinery: "정유 공장",
    Sell: "판매",
    Upgrade: "업그레이드",
    Build: "건설",
    Inspect: "점검",
    Buildings: "건물",
    Iron: "철",
    Actions: "동작",
    FuelType: "연료 선택",
    FuelCost: "연료 비용",
    FuelConsumption: "%{Fuel} 소모량",
    FuelEconomy: "연비",
    FuelProduction: "%{Fuel} 생산량",
    FuelInStorage: "%{Fuel} 보관량",
    Plastic: "플라스틱",
    FuelSurplus: "%{Fuel} 과잉",
    Petrol: "휘발유",
    Buy: "구매",
    NoLiquidity: "유동성 없음",
    NoLiquidityTurnOffAutoSell: "판매하기 위한 %{res}가 부족합니다. 자동 판매 기능이 종료됩니다.",
    Multiplier: "배율",
    MultiplierDesc: "10레벨마다 1배율씩 증가합니다.",
    SellBuilding: "건물 매각",
    PowerGrid: "전력 공급망",
    TradeAmount: "거래 대금",
    SortBy: "정렬",
    SortByPrice: "가격",
    SortByAmount: "수량",
    NotEnoughResourcesForTrade: "이 거래를 위한 거래 센터의 자원이 부족합니다.",
    NotEnoughResources: "이 작업에 필요한 자원이 부족합니다.",
    Transportation: "운송수단",
    Cash: "현금",
    Aluminum: "알루미늄",
    ResearchPoint: "연구 포인트",
    Unlock: "잠금해제",
    BuildingUnlocked: "%{building}이 잠금해제 되었습니다.",
    Science: "과학",
    ScienceFromPowerDesc: "발전소에서 전력을 생산할 때 소량의 연구 포인트를 획득합니다.",
    Culture: "문화",
    School: "학교",
    University: "대학교",
    Polytechnic: "전문대학",
    Colosseum: "콜로세움",
    WindTurbine: "풍력 발전기",
    Engine: "엔진",
    EngineFactory: "엔진 공장",
    CameraFactory: "카메라 공장",
    Camera: "카메라 공장",
    Gun: "총",
    GunFactory: "총기 공장",
    Aircraft: "항공기",
    AircraftFactory: "항공기 공장",
    Zeppelin: "체펠린 비행선",
    ZeppelinFactory: "체펠린 비행선 공장",
    Tank: "탱크",
    TankFactory: "탱크 공장",
    MinimumTradingAmount: "최소 금액보다 낮게 거래할 수 없습니다.",
    CoalPowerPlant: "석탄 발전소",
    PetrolPowerPlant: "가솔린 발전소",
    Copper: "구리",
    Gas: "천연가스",
    GasPump: "천연가스 펌프",
    GasPowerPlant: "천연가스 발전소",
    Missile: "미사일",
    MissileFactory: "미사일 공장",
    Rocket: "로켓",
    RocketFactory: "로켓 공장",
    BuildingPermit: "추가 건설 허가",
    BuildingPermitDesc:
        "%{amount}개의 건물에 대한 허가증이 있으며, 이미 %{amountBuilt}개를 지었고 건설 가능 건수 %{amountLeft}개가 남아 있습니다.",
    BuildingLocked: "아직 건설할 수 없습니다. 먼저 연구센터에서 건물 잠금을 해제해야 합니다.",
    BuildQueue: "건설 대기열",
    BuildQueueDesc: "현재 대기열에 있는 건물 수",
    MaxBuilders: "최대 동시 건설가능",
    MaxBuildersDesc: "동시에 건설할 수 있는 건물 수",
    Silicon: "실리콘",
    AluminumMine: "알루미늄 채굴장",
    CopperMine: "구리 채굴장",
    SiliconMine: "실리콘 채굴장",
    IronMine: "철 채굴장",
    CoalMine: "석탄 채굴장",
    Headquarter: "본부",
    ResearchLab: "연구센터",
    TradeCenter: "무역센터",
    Resources: "자원",
    NotEnoughPower: "💡 전력이 부족합니다. 전원 공급량 증가를 고려하십시오.",
    NotEnoughFuel: "이 작업에 필요한 오일이 부족합니다.",
    NotEnoughCash: "이 작업에 필요한 현금이 부족합니다.",
    NotEnoughSwissMoney: "이 작업에 필요한 스위스 계좌 금액이 부족합니다.",
    BuildingNotEnoughFuel: "💡 %{fuel} 부족",
    AutoSell: "자동 판매",
    SellAll: "모두 판매",
    Change: "변경",
    StatisticsBureau: "통계청",
    LogisticsDepartment: "물류부서",
    From: "From",
    Top20FuelCost: "Top 20 연료 비용",
    To: "To",
    TransportTime: "운송 시간",
    TopN: "Top %{n}",
    Warehouse: "창고",
    TradeWarehouse: "화물 창고",
    Coal: "석탄",
    Video: "비디오",
    ClothingFactory: "의류 공장",
    Clothes: "의류",
    Fashion: "패션",
    FashionFactory: "패션 공장",
    VideoFarm: "비디오 농장",
    SantaFactory: "산타 공장",
    Santa: "산타",
    Car: "차",
    CarFactory: "자동차 공장",
    Ship: "배",
    SolarPanel: "태양 전지판",
    SolarPanelDesc: "💡 태양 전지판은 10초마다 5초만 작동합니다. - 모든 사이클이 정렬됩니다.",
    WindTurbineDesc: "💡 풍력 발전은 10초마다 8초만 작동합니다. - 모든 사이클이 정렬되지 않습니다.",
    Movie: "영화",
    MovieStudio: "영화사",
    Sitcom: "시트콤",
    TVStudio: "방송사",
    PC: "PC",
    GameStudio: "게임 스튜디오",
    Game: "게임",
    ComputerFactory: "컴퓨터 공장",
    Shipyard: "조선소",
    PowerUsage: "전력 소모량",
    PowerSupply: "전력 공급량",
    PowerSurplus: "잉여 전력",
    Level: "레벨",
    Power: "전력",
    CentralBank: "중앙은행",
    ResourceInput: "재료",
    ResourceOutput: "생산",
    ResourceStorage: "저장",
    ResourceChange: "변경",
    ResourceInOutDesc: "💡 재료 건물과 생산 건물을 강조 표시하려면 위의 번호를 누릅니다.",
    ResourceChart: "자원 차트",
    MarketUpdateIn: "마켓 가격 업데이트 까지 남은시간 %{time}",
    Income: "수입",
    Semiconductor: "반도체",
    SemiconductorFactory: "반도체 회사",
    SemiconductorFab: "반도체 공장",
    Steel: "강철",
    Bitcoin: "비트코인",
    BitcoinFarm: "비트코인 채굴장",
    Dogecoin: "도지코인",
    DogecoinFarm: "도지코인 채굴장",
    Guitar: "기타",
    GuitarFactory: "기타 공장",
    Drum: "드럼",
    DrumFactory: "드럼 공장",
    RecordingStudio: "녹음실",
    OperaHouse: "오페라 하우스",
    CoalGasificationPlant: "Coal Gasification Plant",
    GasProcessingPlant: "Gas Processing Plant",
    Music: "음악",
    Glass: "유리",
    PhoneFactory: "전화기 공장",
    Phone: "전화기",
    GlassFactory: "유리 공장",
    Oil: "석유",
    Chromium: "크롬",
    ChromiumMine: "크롬 채굴장",
    Uranium: "우라늄",
    EnrichedUranium: "농축 우라늄",
    NuclearPowerPlant: "원자력 발전소",
    UraniumEnrichmentPlant: "농축 원자력 발전소",
    UraniumMine: "우라늄 채굴장",
    Titanium: "티타늄",
    TitaniumMine: "티타늄 채굴장",
    TitaniumAlloyPlant: "티타늄 합금 발전소",
    ChromiumAlloyPlant: "크롬 합금 발전소",
    Input: "Input",
    PanelPosition: "Panel Position",
    PanelPositionDesc: "왼쪽, 오른쪽 또는 자동에 측면 패널 표시(현재 선택한 타일에 따라 다름)",
    InputCapacity: "입력 용량",
    InputCapacityPerCycle: "입력 용량 / 주기",
    Output: "Output",
    OutputCapacity: "출력 용량",
    OutputCapacityPerCycle: "출력 용량 / 주기",
    ResourceDeposit: "자원 보관",
    RecommendedBuilding: "💡 이 타일에는 %{resource}을 하고 있습니다.",
    AdjacentBonus: "인접 보너스",
    AdjacentBonusDesc: "동일한 유형의 인접한 모든 작업 건물에 대해 %{bonus}%의 추가 용량이 제공됩니다.",
    ConsiderIncreaseProduction: "💡 %{resource} 생산 증가를 고려하십시오.",
    AlwaysTransportInput: "비축 모드",
    AlwaysTransportInputTradeCenter: "항상 수출",
    AlwaysTransportInputTradeCenterDesc:
        "해당 자원에 대해 자동 판매가 활성화되지 않은 경우에도 항상 자원을 무역 센터로 전송",
    AlwaysTransportInputDesc: "최소 생산 요구사항을 초과하더라도 항상 입력 자원 전송",
    ProductionCycleLength: "생산 주기",
    ProductionCycleLengthDesc:
        "한 생산 주기의 지속 시간(초 단위)입니다. 주기를 연장하면 그에 따라 사이클당 입력/출력이 증가하므로 입력 리소스를 가져올 때 우선 순위가 낮아집니다.",
    MaxInputDistance: "최대 입력 거리",
    MaxInputDistanceDesc:
        "이 건물이 입력 자원을 가져올 수 있는 최대 거리(타일 수)",
    AutoSellCapacity: "자동 판매 용량",
    AutoSellCapacityDesc: "자동 판매에서 자원당 초당 처리할 수 있는 최대 자원의 양",
    CurrentAutoSellCapacityMultiplier: "현재 배수: x%{n}",
    AutoSellConcurrency: "동시 자동 판매 갯수",
    AutoSellConcurrencyDesc: "자동 판매에서 동시에 처리할 수 있는 최대 자원의 수",
    MaxAutoSellConcurrencyReached:
        "최대 자동 판매 한계치에 도달했습니다. 이 옵션을 사용하려면 다른 자동 판매를 해제하십시오.",
    CannotSellBuilding: "지금은 건물을 팔 수 없습니다.",
    WallStreet: "월 스트리트",
    MarketCap: "시가총액",
    MarketCapDesc: "총 시가총액(즉, 시장 가치)",
    BuildingValuation: "건물 가치",
    BuildingValuationDesc: "건축 허가 및 업그레이드를 포함한 건물의 총 가치",
    ResourcesValuation: "자원 평가",
    ResourcesValuationDesc: "총 보유중인 자원의 가치",
    Battery: "배터리",
    BatteryFactory: "배터리 공장",
    RatingBuy: "판매",
    RatingSell: "구매",
    SwissShop: "스위스 샵",
    RatingHold: "Hold",
    RatingOutperform: "Outperform",
    RatingUnderperform: "Underperform",
    StockRating: "Stock Rating",
    JetEngine: "제트엔진",
    Helicopter: "헬리콥터",
    Lithium: "리튬",
    LithiumMine: "리튬 채굴장",
    LiionBatteryFactory: "리튬이온 배터리 공장",
    HelicopterFactory: "헬리콥터 공장",
    Satellite: "인공위성",
    ToyFactory: "장난감 공장",
    Toy: "장난감",
    SpaceStation: "우주 정거장",
    SpaceStationFactory: "우주정거장 공장",
    OperatingSystem: "Operating System",
    OperatingSystemCompany: "Operating System Inc",
    LinuxDistribution: "Linux Distribution",
    Internet: "인터넷",
    WebBrowser: "웹 브라우저",
    Console: "콘솔",
    ConsoleFactory: "콘솔 공장",
    Train: "기차",
    TrainFactory: "기차 공장",
    ShoeFactory: "신발 공장",
    Shoes: "신발",
    ArtilleryFactory: "대포 공장",
    Artillery: "대포",
    SubmarineFactory: "잠수함 공장",
    Submarine: "잠수함",
    Spaceship: "우주비행선",
    RobotFactory: "로봇 공장",
    Robot: "로봇",
    SpaceshipFactory: "우주비행선 공장",
    SatelliteFactory: "인공위성 공장",
    JetEngineFactory: "제트엔진 공장",
    StockRatingDesc:
        "시장 자본에 영향을 미치고 시장과 함께 업데이트되는 월 스트리트 분석가들의 주식 등급 합의",
    InterestRate: "익일이자율",
    InterestRateDesc: "당신이 오프라인 상태일 때 예상 이자율",
    OfflineEarning: "오프라인 수입",
    OfflineEarningDesc: "오프라인 수익은 시가총액과 이자율에 따라 달라집니다.",
    PerMin: "%{amount}/min",
    OfflineEarningTime: "오프라인 수익 시간",
    OfflineEarningTimeDesc: "최대 이 임계값에 대해 오프라인 수입을 얻게 됩니다.",
    BuyPermit: "건축 허가서",
    NotEnoughBuildingPermit: "새 건물을 더 짓기 위해 건축 허가서를 구매해주세요.",
    MovingAverage: "평균 이동",
    MovingAverageDesc: "실시간으로 반영되는 자원의 평균 이동량",
    AllowZoom: "확대",
    AllowZoomDesc: "확대/축소 지원을 켭니다. 마우스 휠을 사용하여 확대/축소합니다. 현재 줌은 %{zoom}입니다.",
    AllowZoomMobileDesc: "확대/축소 지원을 켭니다. 꼬집어서 확대/축소할 수 있습니다. 현재 줌은 %{zoom}입니다.",
    Settings: "설정",
    SellBuildingDesc:
        "건물을 팔면 투자금의 50%가 환불되고 자원의 50%가 무역 센터로 운반됩니다.",
    SellBuildingFullRefundDesc:
        "건물 재활용 정책이 활성화되어 있습니다. 건물을 팔면 %{time}까지 전액 환불됩니다.",
    Sound: "사운드 효과",
    SoundDesc: "클릭음이나 오류 소리 같은 효과음 켜기",
    AutoHighlight: "자동 강조 표시",
    AutoHighlightDesc: "건물을 선택할 때 동일한 유형의 건물 자동으로 강조 표시",
    MusicDesc: "음악 끄기: It's Not Over 'Til The Bossa Nova by Shane Ivers (https://www.silvermansound.com)",
    Credits: "크레딧",
    Icons: "아이콘",
    MisplacedBuilding: "⛔ 이 %{building}은(는) 올바른 자원 영역 위에 배치되지 않았습니다.",
    UnderConstruction: "%{building}이(가) 건설 중입니다.",
    Left: "왼쪽",
    Right: "오른쪽",
    Auto: "자동",
    HighlightBuildings: "건물 강조 표시",
    HighlightTurnedOff: "...그것은 폐쇄됩니다.",
    HighlightStockpileModeOn: "... 비축 모드가 설정되었습니다.",
    HighlightWarehouseOnly: "...창고만을 위한 것입니다.",
    HighlightProductionCycleNotDefault: "...생산주기가 1을 초과한 경우",
    HighlightMaxInputDistanceNotDefault: "...최대 입력 거리가 무한보다 작습니다.",
    HighlightNotMakingProfit: "...이익을 남기지 않습니다.",
    NBuildingsAreHighlighted: "%{n}개의 건물이 강조 표시됩니다.",
    OnlyToWarehouse: "창고 전용",
    OnlyToWarehouseDesc: "이 건물에서 자원을 창고에게만 전송합니다.",
    TurnOffProduction: "폐쇄",
    TurnOffProductionDesc:
        "건물의 생산을 중단하고, 더 이상 자원을 수송하지 않습니다. 또한 전력도 사용하지 않습니다.",
    ApplyToAll: "모든 %{building}에 적용",
    FuelCostNumber: "%{cost} %{fuel}",
    Unlimited: "Unlimited",
    Transport: "Transport",
    TileModifier: "Tile Modifier",
    ShowAllModifiers: "Show All Modifiers",
    HideAllModifiers: "Hide All Modifiers",
    NumberOfBuildings: "Number of buildings you have",
    ShowContent: "Show Content",
    HideContent: "Hide Content",
    BuyExpansionPack: "Buy For %{price}",
    Cities: "Cities",
    WarehouseInputCapacityDesc: "Amount of resources the warehouse can transport inward per second, per resource.",
    WarehouseBuildDesc: "Warehouses can transport and store any resources",
    InputStrategy: "Input Strategy",
    InputStrategyClose: "Closer",
    InputStrategyCloseDesc: "Prefer the closest warehouse which has enough resources",
    InputStrategyFar: "Farther",
    InputStrategyFarDesc: "Prefer the farthest warehouse which has enough resources",
    InputStrategyAmount: "Amount",
    InputStrategyAmountDesc: "Prefer the warehouse with the largest amount of the resources, regardless of distance",
    FuelCostSave: "Fuel Cost Save",
    FuelCostSaveDesc:
        "Warehouses save a certain percentage of fuel for transporting resources inward compared to other buildings, the higher the level, the more the save",
    SoftwareCompany: "Software Company",
    Software: "Software",
    ScreenFactory: "Screen Factory",
    Screen: "Screen",
    JoinDiscord: "Join our Discord server for latest updates, tips and discussions",
    ClaimOfflineEarning: "Claim Offline Earning",
    OfflineTime: "Offline Time",
    Minutes: "%{time}min",
    MaxUpgrade: "Max Upgrade",
    MaxUpgradeDesc: "You have reached maximum upgrade",
    ClaimAmount: "Cash +%{amount}",
    EarningPerMinute: "Earning Rate",
    EffectiveTime: "Effective Time",
    EffectiveTimeDesc: "Your effective offline earning time is capped at %{time}min.",
    BuildSearchPlaceholder: "Type building or resource to search",
    MineOverlayWarning: "%{building} is not affected by tile modifier",
    WholesaleCenter: "Wholesale Center",
    OrderFrom: "Order from %{name}",
    ExpireIn: "Expire In",
    ProfitMargin: "Profit Margin",
    NotMakingProfitWarning: "💡 Production not profitable, consider shut it down",
    TurnOnAllProductions: "Production On",
    TurnOnAllProductionsDesc: "Turn on productions of all buildings, cannot be used when Cost Saver policy is active",
    OperationSuccessful: "This operation has been successfully completed",
    TurnOn: "Turn On",
    Reward: "Reward",
    PerSecond: "%{time}/s",
    PerCycle: "%{amount}/cycle",
    PolicyPoint: "Policy Point",
    PolicyPointPerMinute: "Generate Rate",
    PolicyPointPerMinuteDesc: "You acquire policy points every minute in the game",
    YourWilLGaimPolicyPoints: "You will gain %{amount} policy points in %{time}s",
    PolicyPointDesc: "💡 The more active policies, the more cost for each policy",
    NextOrderIn: "Next Order In",
    FillOrder: "Fill Order",
    RejectOrder: "Pass",
    YouHave: "You have %{amount}",
    WholesaleCenterLocked:
        "You need at least %{required} different resources to unlock Wholesale Center. You only have %{current} resources",
    OrderFilled: "The order from %{from} has been successfully filled!",
    PolicyCenter: "Policy Center",
    NewOrder: "A new order from %{from} has arrived, please check in Wholesale Center",
    Policies: "Policies",
    PolicyNotEnoughTime: "You don't have enough policy points for this policy",
    TimeLeft: "%{time} Left",
    WholesaleCenterOrderFaster: "World's Fair",
    WholesaleCenterOrderFasterDesc: "Wholesale Center receives orders 2x faster and the order size is 2x bigger",
    PolicyOilWellPowerx2: "Supercharge Oil Well",
    PolicyOilWellPowerx2Desc: "Oil wells produce 2x oil and use 2x power",
    HalfTransportSpeed: "Slow Down To Save Up",
    HalfTransportSpeedDesc: "Transportation speed is slowed down by 25% and fuel cost is reduced by 25%",
    RefineryMoreOil: "Mo Petrol Mo Problems",
    RefineryMoreOilDesc: "Oil Refineries produce 50% more petrol and 50% less plastic",
    StickyInput: "Sticky Input",
    StickyInputDesc:
        "Buildings will prefer to transport from previous source, instead of searching for the best source every cycle (FREE POLICY)",
    RefineryMorePlastic: "Mo Plastics Mo Problems",
    RefineryMorePlasticDesc: "Oil Refineries produce 50% less petrol and 50% more plastic",
    FreeOilTransport: "Free Oil Transport",
    FreeOilTransportDesc: "Oil transport doesn't cost fuel but oil wells use 2x power",
    SuperSteelMill: "Hearts of Iron",
    SuperSteelMillDesc: "Steel mills use 50% less coal and 25% more iron and 25% more power",
    AlSemiconductor: "Al Circuit",
    AlSemiconductorDesc: "Circuit foundries use aluminum instead of copper",
    CostSaver: "Cost Saver",
    CostSaverDesc: "If a building's input cost more than its output, shut down the production",
    CostSaverBuildingDesc:
        "Cost Saver policy is active, production will turn on/off automatically based on its profitability",
    CostSaverBuildingWarning: "Cost Saver policy is active, you cannot manually change production",
    GlassUseCoal: "Black Glass",
    GlassUseCoalDesc: "Glass factories use 50% more coal and 50% less silicon",
    AdjacentBonusOnlyOutput: "Adjacent Bonus Plus",
    AdjacentBonusOnlyOutputDesc:
        "Adjacent bonus does not require more input but uses more power and is only 50% effective",
    IronMine2xOutput: "Heavy Iron",
    IronMine2xOutputDesc: "Iron mines produce 2x iron but iron transport costs 2x fuel",
    SolarPanelAlwaysWork: "The Sun Never Sets",
    SolarPanelAlwaysWorkDesc: "Solar panel works 100% of the time but produces 60% less power",
    SteelScience: "Knowledge Through Steel",
    SteelScienceDesc: "Steel mills use 2x input and produce extra science",
    ShowWarehouse: "Unlock Warehouse",
    ShowWarehouseDesc:
        "A warehouse is a special building that only transports and store resources and can provide fuel save (FREE POLICY)",
    WholesaleCenterProducingOnly: "Wholesale Partners",
    WholesaleCenterProducingOnlyDesc:
        "Wholesale center orders only contain resources that are currently being produced (you also need to be producing the number of required resources to unlock wholesale center)",
    ShoppingSpree: "Shopping Spree",
    ShoppingSpreeDesc:
        "If a resource's output capacity falls short, buy the shortage amount from Trade Center automatically (If the resource has auto sell on, it will be ignored)",
    ShoppingSpreeTradeCenterDesc:
        "💡 Shopping Spree policy is on, Trade Center will automatically buy resources in shortage",
    ExtraPolicyPoints: "Political Lobbyist",
    ExtraPolicyPointsDesc: "Increase policy point production capacity by 50%",
    CrAlloyUseFe: "Chroiron",
    CrAlloyUseFeDesc: "Chromium alloy plants do not use Lithium but use 2x Iron instead",
    DoubleTileModifier: "Nature's Power",
    DoubleTileModifierDesc: "All tiles' modifier's effect x2 - both positive and negative",
    TileModifierOutputOnly: "Tile Modifier Plus",
    TileModifierOutputOnlyDesc:
        "Tile modifiers only affect output instead of both input and output but are only 50% effective",
    GasPlantPetrol: "Gas Liquidizer",
    GasPlantPetrolDesc: "Gas power plants use extra gas to produce petrol",
    BuildingRecycle: "Building Recycle",
    BuildingRecycleDesc: "Get full refund when you sell a building within 1 min after construction",
    CoalPlantFuel: "Coal Liquidizer",
    CoalPlantFuelDesc: "Coal power plants use extra coal to produce petrol",
    Welcome: "Welcome",
    SeeTutorialAgain: "Redo Tutorial",
    ReadSteamGuide: "Official Guide on Steam",
    HelpTranslateTheGame: "Help Translate the Game🌐",
    SkipTutorial: "Skip Tutorial",
    NextTutorial: "Next",
    Tutorial1:
        "Industry Idle is a <em>resource management</em> game where you build factories🏭, produce goods📦 and make money💸.<br><br>Let's go through some basic concepts to get you started - it won't take long, I pinky promise.",
    Tutorial2:
        "All buildings need power⚡, you have a <em>wind turbine</em> that generates power. You can see your current power supply on the left side of the top bar.<br><br>You might have noticed that wind turbines only work <em>80%</em> of the time. You can consider building other types of power plants that generate stable power.",
    Tutorial3:
        "You have a lot of <em>resource deposits</em> on the map. To extract resources, you have to build mines⛏️ <em>on top of</em> the corresponding deposit.<br><br>For example, you have an <em>oil well🛢️</em> that extracts <em>oil</em> from an oil deposit.<br></br>Resource deposits are unlimited - no need to worry about them running out. Apart from mines, other buildings can be built on any empty tile.",
    Tutorial4:
        "Resource transportation costs fuel. On this map, you can use <em>petrol⛽</em> as fuel. You have an <em>oil refinery</em> that transports oil from the oil well and produces petrol.<br><br>The tiny moving <em>dots</em> represent the real-time movement of resources. You should optimize your building locations to minimize the distance of travel.<br><br><em>Upgrading</em> your buildings will increase their output, but will also increase their power usage and input required.<br><br>You can change your fuel type in the transportation center🚦. Remember to make sure your fuel production is above consumption otherwise your production will halt when you run out of fuel.",
    Tutorial5:
        "To make money, you need to export your resources via the trade center. To do this, simply turn on <em>auto sell</em> for that resource.<br></br>You can also buy resources from the trade center as well. Remember <em>if you buy a resource, you will drive up the price</em> and if you sell a resource, you will drive down the price.<br><br>The market is <em>volatile</em> and the price📈 changes regularly.",
    Tutorial6:
        "To build new buildings, you need to unlock it first in the <em>research lab🧪</em>. The research lab also converts science to research points.<br><br>Your wind turbine (and other power plants) produces a small amount of science when running. And you can build school🏫 and other dedicated buildings to boost science later.<br><br>Now you have learned all the basics, start to build up your economy! Here are some <em>cash💸</em> and <em>petrol⛽</em> to give you a jump start.",
    WelcomePlay: "Play",
    WelcomePlayMuted: "Play (🔇Music)",
    Changelog: "Changelog",
    ChangelogGotIt: "Got It",
    Chat: "Chat",
    Send: "Send",
    Import: "Import",
    Export: "Export",
    SteamCloudBackup: "Steam Cloud Backup",
    LastBackupAt: "Last Backup",
    RestoreFromBackup: "Restore from Backup",
    RestoreFromBackupFail: "Failed to restore backup from Steam Cloud: are you sure there's a backup?",
    RestoreFromBackupTitle: "Are you sure?",
    RestoreFromBackupDesc:
        "You normally don't need to restore from cloud backup, unless your local save is lost. Cloud backup are a bit older than your local save",
    ChatMessages: "Chat Messages",
    ChatPlaceholder: "Type your message: max 100 chars",
    ChangeName: "Change",
    SaveName: "Save",
    NameValidationRule: "Your name should only contain letters and numbers and be between 5-15 chars",
    NameValidationRuleProfanity: "Your name should not contain profanity",
    ChatMessageRateLimit: "You can only send a new chat message every 10 seconds",
    NameSaved: "Your name has been changed successfully",
    NoMessages: "No new messages",
    Leaderboard: "Leaderboard",
    LeaderboardDesc: "The leaderboard score is all the Swiss money you've ever earned",
    Name: "Name",
    Rank: "Rank",
    Tips1: "주식 등급은 5단계입니다. 구매, 성능 초과, 보류, 성능 미달 및 판매",
    Tips2:
        "비축 모드를 켜지 않는 한, 생산량이 충분하다면 빌딩은 자원 수송을 중단할 것입니다.",
    Tips3: "자원 수송을 위한 연료 비용은 자원 거리 및 양에 따라 결정됩니다.",
    Tips4: "지도에서 발견된 양이 입력 용량을 초과하는 경우에만 건물이 자원을 전송합니다.",
    Tips5: "건물은 해당 자원에 대해 자동 판매가 해제된 경우에만 무역 센터에서 자원을 전송합니다.",
    Tips6: "해당 입력 용량 섹션에서 자원의 연료 비용을 확인할 수 있습니다.",
    Tips7: "자원을 구입하면 가격을 올릴 수 있습니다. 자원을 판매하면 가격을 낮출 수 있습니다.",
    Tips8: "각 자원의 양과 시간에 따른 변화에 대한 차트를 통계청에서 볼 수 있습니다.",
    Tips9: "건물에 필요한 연구 포인트는 투입 자원의 시장 가격에 의해 결정됩니다.",
    Tips10: "시장마다 자원 가격이 다릅니다. 항상 시장 변동성에 대비하십시오.",
    Tips11: "생산을 확장하기 전에 항상 전원 및 연료 공급을 점검하는 것이 좋습니다.",
    FPS30: "Energy Saving",
    OfflineModeDesc:
        "Cannot connect to the server: offline earnings will not be generated. Please check your internet connection",
    OptOut: "Opt Out",
    OptIn: "Reset and Enable",
    LeaderboardOptOut: "Leaderboard Opt-Out",
    LeaderboardOptOutDesc:
        "This will no longer send leaderboard score. PLEASE NOTE: if you want to enable leaderboard later, your data needs to be reset",
    LeaderboardOptIn: "Reset and Enable Leaderboard",
    LeaderboardOptInDesc: "Your data needs to be RESET before you can re-enable leaderboard, are you sure?",
    RewardAdsFailed: "Reward video did not complete",
    RewardAdsNotAvailable: "Reward video is not available (currently only iOS/Android is supported)",
    OfflineEarningDoubleSuccess: "You have doubled your offline earning",
    FPS30Desc:
        "Turn on energy saving mode will run the game at 30FPS instead of 60FPS. This will make your battery last longer",
    HighlightAll: 'Highlight "%{type}"',
    HighlightInput: "🔍 Highlight %{type} Input",
    HighlightOutput: "🔍 Highlight %{type} Output",
    TotalInput: "Total Input Capacity",
    TotalOutput: "Total Output Capacity",
    RunOutIn: "Out in %{time}",
    FuelRunOutWarning: "💡 Your fuel consumption exceeds production. When fuel runs out, your transportation will halt",
    InAmount: "In: %{number}",
    OutAmount: "Out: %{number}",
    SwissBank: "Swiss Bank",
    SwissMoney: "%{money} 💵",
    PrestigeDesc: "If you start in a new city, you will get %{money} 💵",
    RestorePurchases: "Restore Purchases",
    RestorePurchasesSuccess: "Your purchases have been restored",
    RestorePurchasesFailed: "Your purchases did not restore",
    ExpansionPacks: "Expansion Packs",
    ExpansionPack1: "Expansion Pack 1",
    ExpansionPack1Owned: "Expansion Pack 1",
    RequireExpansionPack1: "Expansion Pack 1",
    RequireExpansionPack1Desc: "This is only available for Expansion Pack 1",
    RequireAnyExpansionPack: "Expansion Packs Exclusive",
    RequireAnyExpansionPackDesc: "This feature requires you to own at least one of the expansion packs",
    HideRewardAd: "Hide Rewarded Ads",
    HideRewardAdDesc:
        "All in-game ads are optional rewarded ads. This will hide all the rewarded ad options from game.",
    HideDiscordBanner: "디스코드 배너 숨기기",
    HideDiscordBannerDesc: "Hide Discord and storefront banner in the headquarter",
    HideChat: "Hide Chat Message",
    HideChatDesc: "Hide chat message from the bottom toolbar",
    SortedByDeficit: "Sorted By Deficit",
    PurchaseFailed: "The purchase did not complete",
    PurchaseSteamContinue: "Please finish your purchase on Steam",
    PurchaseSuccess: "The purchase has completed, thanks for your support",
    PrestigeCurrency: "Swiss Money 💵",
    RestartDesc: "💡 다시 시작할까요? 위의 새 도시에서 시작을 누르고 현재 도시를 선택할 수 있습니다.",
    PrestigeGoBack: "Go Back",
    PermanentUpgradeDesc: "This upgrade will carry over if you start in a new city",
    ProductionMultiplier: "Production Multiplier",
    ProductionMultiplierDesc:
        "모든 건물의 생산 능력 향상(채굴장, 공장, 발전소, 과학 및 문화 건물 포함)",
    FuelCostDiscount: "Fuel Cost Discount",
    FuelCostDiscountDesc: "Gives a discount to fuel cost when transporting resources",
    AutoSellCapacityMultiplier: "Auto Sell Capacity Multiplier",
    AutoSellCapacityMultiplierDesc:
        "현재 용량과 상관없이 자동 판매 용량에 적용되는 배수",
    BuildingPermitCostDivider: "Building Permit Cost Divider",
    BuildingPermitCostDividerDesc: "Divide building permit cost by this divider",
    ExtraAdjacentBonus: "Extra Adjacent Bonus",
    ExtraAdjacentBonusDesc: "동일한 유형의 모든 인접 작업 건물에 대한 추가 보너스 용량",
    OfflineEarningMultiplier: "Offline Earning Multiplier",
    OfflineEarningMultiplierDesc: "A multiplier that applies to offline earnings",
    PrestigeAlertTitle: "Are you sure?",
    PrestigeAlertContent:
        "Your company will be liquidated. You will cash in %{amount} Swiss money and start a new company in %{city}",
    PrestigeCurrencyDesc:
        "This is the money in your secret Swiss bank account, you can carry it with you when you start in a new city",
    Prestige: "Cash In",
    Cancel: "Cancel",
    SaveFileCorrupted: "Save File Corrupted",
    CheatDetected: "이전 저장소가 서버 유효성 검사를 통과하지 못하여 읽을 수 없습니다. 새 저장으로 시작합니다.",
    LoadGameError: "Failed to Load Game",
    LoadGameErrorMessage: "Error message: %{message}",
    LoadGameErrorDesc: "인터넷 연결을 확인하십시오. 문제가 지속되면 문의하십시오.",
    ExpansionPackIncompatible:
        "You are importing a save with expansion packs but your game doesn't have the required expansion packs",
    SaveFileMigrated: "A New Era: Beta Is Here",
    SaveFileMigratedDesc:
        "Thank you for play testing in alpha. Your old map is not compatible but we have migrated your data and give you some bonus",
    ClaimSwissMoney: "Claim %{amount} Swiss Money 💵",
    SaveFileMigratedFinePrint:
        "Your market cap is converted to Swiss Money and your unspent Swiss money is carried forward. You will get 50% bonus Swiss money for play testing in alpha. Max Swiss money that can be carried forward is capped at 200",
    CashIn: "Cash In",
    CurrentCity: "Current City",
    CashInDesc:
        "Your will get this amount to your Swiss bank account if you start in a new city. It is based on your company's market cap and it must reach %{amount} before you can earn Swiss money",
    MoveToNewMap: "Start In A New City",
    CityName: "도시",
    CitySize: "맵 크기",
    GridType: "Grid Type",
    StartInThisCity: "Start In %{city}",
    CityBonus: "도시 보너스",
    ResourceTilePercentage: "Resource Tiles",
    MapSquareGrid: "Square",
    MapHexGrid: "Hex",
    Translator: "번역가",
    TranslatorName: "SK HYNIX M16 ETCH",
    Language: "언어",
    ThisLanguage: "한국어",
    Stockholm: "스톡홀름",
    StockholmBonus:
        "<li>Free level 4 wind turbine x1</li><li>Free level 4 oil well x1</li><li>Free level 2 oil refinery x1</li><li>Paper mills are unlocked</li><li>Logging camps have 2x output</li>",
    Rotterdam: "Rotterdam",
    RotterdamBonus:
        "<li>Steel Mills have 2x capacity</li><li>Stainless Steel Plants have 2x capacity</li><li>Free iron transportation</li><li>Steel transportation costs 50% less fuel</li><li>Start with 2x auto sell capacity</li><li>No tile modifiers</li>",
    Oslo: "Oslo",
    OsloBonus:
        "<li>Oil refineries have 2x capacity</li><li>Gas processing plants have 2x capacity</li><li>Petrol power plants have 2x capacity</li><li>Steel mills use natural gas instead of coal</li><li>Free oil transportation</li>",
    StPetersburg: "St. Petersburg",
    StPetersburgBonus:
        "<li>Uranium mines have 2x output</li><li>Uranium enrichment plants have 2x capacity</li><li>Uranium transportation costs 50% less fuel</li><li>Free gun transportation</li><li>Missile factories use enriched uranium instead of titanium and uranium</li>",
    Hamburg: "Hamburg",
    HamburgBonus:
        "<li>Zeppelin factories are unlocked</li><li>Semiconductor factories have 2x productivity</li><li>Shipyards have 2x capacity</li><li>Car factories have 2x capacity</li><li>Li-ion battery factories are unlocked</li>",
    Toulouse: "Toulouse",
    ToulouseBonus:
        "<li>Titanium mines have 2x output</li><li>Uranium enrichment plants have 2x productivity</li><li>Jet engine factories have 2x capacity</li><li>Aircraft factories have 2x productivity</li><li>Rocket factories use uranium instead of enriched uranium</li>",
    Rome: "Rome",
    RomeBonus:
        "<li>Colosseums are unlocked</li><li>Colosseums have 2x productivity</li><li>Start with level 5 policy center</li><li>Opera houses have 2x capacity</li><li>Recording studios also produce culture</li>",
    Detroit: "Detroit",
    DetroitBonus:
        "<li>Engine factories are unlocked</li><li>Engine factories have 2x productivity</li><li>Car factories have 2x capacity</li><li>Car factories do not need batteries</li><li>Train factories have 2x capacity</li>",
    Boston: "Boston",
    BostonBonus:
        "<li>Start with level 5 research lab</li><li>Polytechnics are unlocked</li><li>Polytechnics have 2x capacity</li><li>Schools have 2x capacity</li><li>University have 2x productivity</li>",
};
